### ISSUE TITLE
Remove all references to HTTP://

### ISSUE THREAD

**Issue by grantpezeshki** [nycehs/Closerlook-Deployment#1]
One of the issues coming up on security scan is that we refer users to other site content with static links to our current production site. When we transition to the new secure host, all these links will break. Linking from a secure site to non ssl sites is also frowned upon, so in general we should replace all HTTP:// references with relative references or secure HTTPS:// links.

**Comment by mmontesanonyc** [comment]
With [recent commit](https://github.com/nycehs/Closerlook-Deployment/commit/4ba23b5ab2163d967fada70893771d762deec368), did the following for all data stories:

- Replaced portal links with relative references 
- checked that all nyc.gov links in the template using http: could use https: instead
- found-and-replaced them for all data stories
